version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: attendance_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: attendance_backend
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql+pymysql://root:root@mysql:3306/attendance_system
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      FRONTEND_ORIGIN: http://13.235.91.178:3000
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - /app/__pycache__
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./attendance-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    container_name: attendance_frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
  uploads_data: