"use client";

import { useEffect, useState } from "react";
import { Eye, FilePlus2, Send } from "lucide-react";
import toast from "react-hot-toast";
import api, { getErrorMessage } from "@/lib/api";
import { type AppointmentLetterValues } from "@/lib/appointmentLetterPdf";

type Employee = { id: number; name: string; designation: string; department: string; created_at: string; role: string };
const companyAddress = "D1, Plot No. 275, Shree Samarth CHS, Gorai 2, Mumbai - 400091";
const dateValue = (date: Date | string) => new Date(date).toLocaleDateString("en-GB");

export function AppointmentLetterPreview({ values }: { values: AppointmentLetterValues }) {
  return <article className="mx-auto min-h-760px max-w-760px bg-white p-6 font-serif text-[13px] leading-relaxed text-slate-900 shadow-sm sm:p-10"><header className="border-b-4 border-orange-500 pb-4"><div className="flex items-start justify-between gap-4"><div><div className="text-3xl font-bold"><span className="text-orange-500">Prop</span><span className="text-blue-900">Checkup</span></div><p className="text-xs font-semibold text-orange-600">India&apos;s First Home Inspection Startup</p></div><div className="text-right font-sans text-xs text-blue-900"><p>www.propcheckup.com</p><p>info@propcheckup.com</p><p>+91- 8689868659</p></div></div></header><h1 className="my-5 text-center text-xl font-bold">APPOINTMENT LETTER</h1><p>Date: <strong className="underline">{values.letter_date}</strong></p><p className="mt-3"><strong>Company Address</strong> - {values.company_address}</p><p className="mt-5">To,</p><p className="font-bold underline">{values.employee_name}</p><p className="mt-3 font-bold">› Subject: Appointment for the Position of {values.designation}</p><p className="mt-3">Dear <strong className="underline">{values.employee_name}</strong>,</p><p className="mt-3">We are pleased to offer you the position of <strong>{values.designation}</strong> at <strong>PropCheckup</strong>. Based on your qualifications and experience, we believe you will be a valuable addition to our team.</p><ul className="mt-3 list-disc space-y-1 pl-6"><li>Your appointment will be effective from <strong className="underline">{values.start_date}</strong>. You will be working at our <strong className="underline">{values.office_location} / {values.department}</strong>.</li><li>Your compensation details are as follows: <strong className="underline">Salary: {values.salary} per month/year</strong></li><li>Your working hours will be from <strong className="underline">{values.working_hours}</strong>, <strong className="underline">{values.working_days}</strong>.</li></ul><p className="mt-5">You are expected to comply with company policies, rules, and regulations at all times. Any breach may result in disciplinary action. Kindly sign and return a copy of this letter as a token of your acceptance.</p><p className="mt-3">We look forward to having you on our team and wish you a successful career with us.</p><p className="mt-3">Sincerely,</p><p className="mt-6 font-bold underline">{values.authorized_signatory}</p><p className="font-bold">PropCheckup</p><p className="mt-6 font-bold">› Employee Acceptance</p><p className="mt-3">I, <strong className="underline">{values.employee_name}</strong>, accept the terms and conditions mentioned above.</p><p className="mt-3">Signature: ____________________ &nbsp;&nbsp;&nbsp;&nbsp; Date: ______________</p><footer className="mt-12 -mx-6 bg-blue-950 px-4 py-2 text-center font-sans text-[10px] text-white sm:-mx-10">Office No.62, Xth Central Mall, 2nd Floor, Above Kotak Bank, Mahavir Nagar, Kandivali West, Mumbai – 400067</footer></article>;
}

export default function AppointmentLetterGenerator() {
  const [employees, setEmployees] = useState<Employee[]>([]); const [employeeId, setEmployeeId] = useState(""); const [saving, setSaving] = useState(false);
  const [values, setValues] = useState<AppointmentLetterValues>({ employee_name: "", designation: "", department: "", office_location: "", start_date: "", letter_date: dateValue(new Date()), company_address: companyAddress, salary: "", working_hours: "9:30 AM to 6:30 PM", working_days: "6 days of the week", authorized_signatory: "Authorized Signatory" });
  useEffect(() => { api.get("/users/").then(({ data }) => setEmployees(data.filter((employee: Employee) => employee.role === "user"))).catch(error => toast.error(getErrorMessage(error))); }, []);
  const selectEmployee = (id: string) => { setEmployeeId(id); const employee = employees.find(item => String(item.id) === id); if (employee) setValues(previous => ({ ...previous, employee_name: employee.name, designation: employee.designation, department: employee.department, start_date: dateValue(employee.created_at) })); };
  const update = (key: keyof AppointmentLetterValues, value: string) => setValues(previous => ({ ...previous, [key]: value }));
  const save = async (send: boolean) => { if (!employeeId) return toast.error("Select an employee"); setSaving(true); try { await api.post("/employee-documents/letters/appointment", { employee_id: Number(employeeId), ...values, send }); toast.success(send ? "Appointment letter sent to employee documents" : "Appointment letter draft saved"); } catch (error) { toast.error(getErrorMessage(error)); } finally { setSaving(false); } };
  const fields: [keyof AppointmentLetterValues, string][] = [["employee_name", "Employee Name"], ["designation", "Job Title"], ["department", "Department"], ["office_location", "Office Location / Place of Posting"], ["start_date", "Start Date"], ["letter_date", "Letter Date"], ["salary", "Salary"], ["working_hours", "Working Hours"], ["working_days", "Working Days"], ["authorized_signatory", "Authorized Signatory"], ["company_address", "Company Address"]];
  return <div className="space-y-6"><section className="rounded-xl border border-ink-200 bg-white p-4 shadow-card sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Appointment Letter</h2><p className="text-sm text-ink-500">Select an employee, edit the details, preview, then save a draft or send the letter.</p></div><FilePlus2 className="text-brand-600" /></div><label className="mt-5 block max-w-md text-sm font-medium">Select Employee<select value={employeeId} onChange={event => selectEmployee(event.target.value)} className="mt-1 block w-full rounded-lg border-ink-200"><option value="">Select employee</option>{employees.map(employee => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></label></section>{employeeId && <div className="grid gap-6 xl:grid-cols-[340px_minmax(0,1fr)]"><section className="rounded-xl border border-ink-200 bg-white p-5 shadow-card"><h3 className="font-semibold">Editable letter details</h3><p className="mb-4 text-xs text-ink-500">Changes apply only to this appointment letter.</p><div className="space-y-3">{fields.map(([key, label]) => <label key={key} className="block text-xs font-medium text-ink-600">{label}<input value={values[key]} onChange={event => update(key, event.target.value)} className="mt-1 block w-full rounded-lg border-ink-200 text-sm" /></label>)}</div><div className="mt-5 grid gap-2"><button onClick={() => save(false)} disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-lg border border-ink-300 px-4 py-2.5 text-sm font-medium"><Eye size={16}/> Generate Draft</button><button onClick={() => save(true)} disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50"><Send size={16}/> Send to Employee</button></div></section><div className="rounded-xl border border-ink-200 bg-ink-100 p-3 sm:p-6"><p className="mb-3 text-sm font-semibold text-ink-700">Preview Appointment Letter</p><div className="overflow-x-auto"><AppointmentLetterPreview values={values} /></div></div></div>}</div>;
}
